# Generated by Django 5.2.7 on 2025-10-04 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chat",
            options={"ordering": ["-updated_at"]},
        ),
        migrations.AlterModelOptions(
            name="chatmessage",
            options={"ordering": ["created_at"]},
        ),
        migrations.AddField(
            model_name="chat",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("ar", "Arabic")],
                default="en",
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="chat",
            name="model_type",
            field=models.CharField(
                choices=[
                    ("gemini", "Google Gemini"),
                    ("deepseek", "DeepSeek"),
                    ("llama", "Meta Llama"),
                    ("gpt-4", "OpenAI GPT-4"),
                    ("claude", "Anthropic Claude"),
                ],
                default="gemini",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="chat",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="chat",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chats",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="model_used",
            field=models.CharField(
                blank=True,
                help_text="Specific model used for this message",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="tokens_used",
            field=models.IntegerField(
                blank=True,
                help_text="Number of tokens used for this message",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="role",
            field=models.CharField(
                choices=[
                    ("assistant", "Assistant"),
                    ("user", "User"),
                    ("system", "System"),
                ],
                max_length=15,
            ),
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ai_summary",
                    models.TextField(
                        blank=True,
                        help_text="AI-generated summary of user interactions",
                        null=True,
                    ),
                ),
                (
                    "preferred_model",
                    models.CharField(
                        blank=True,
                        help_text="User's preferred AI model",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "preferred_language",
                    models.CharField(
                        choices=[("en", "English"), ("ar", "Arabic")],
                        default="en",
                        max_length=5,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
