# Generated by Django 5.2.7 on 2025-10-04 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_chat_options_alter_chatmessage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='model_type',
            field=models.CharField(choices=[('gemini', 'Google Gemini'), ('deepseek', 'DeepSeek'), ('llama', 'Meta Llama'), ('gpt-4', 'OpenAI GPT-4'), ('claude', 'Anthropic Claude'), ('groq', 'Groq (Llama 3.3)')], default='gemini', max_length=50),
        ),
    ]
